{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PhiToGraph.
--   Generated by the BNF converter.

module PhiToGraph.Syntax.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified PhiToGraph.Syntax.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print PhiToGraph.Syntax.Abs.Ident where
  prt _ (PhiToGraph.Syntax.Abs.Ident i) = doc $ showString i

instance Print PhiToGraph.Syntax.Abs.Term where
  prt i = \case
    PhiToGraph.Syntax.Abs.TermAttr id_ -> prPrec i 0 (concatD [prt 0 id_])
    PhiToGraph.Syntax.Abs.TermMap id_ term -> prPrec i 0 (concatD [prt 0 id_, doc (showString "->"), prt 0 term])
    PhiToGraph.Syntax.Abs.TermObj terms -> prPrec i 0 (concatD [doc (showString "["), prt 0 terms, doc (showString "]")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [PhiToGraph.Syntax.Abs.Term] where
  prt = prtList

instance Print PhiToGraph.Syntax.Abs.Commands where
  prt i = \case
    PhiToGraph.Syntax.Abs.Commands commands -> prPrec i 0 (concatD [prt 0 commands])

instance Print PhiToGraph.Syntax.Abs.Command where
  prt i = \case
    PhiToGraph.Syntax.Abs.CommandAdd n -> prPrec i 0 (concatD [doc (showString "ADD"), doc (showString "("), prt 0 n, doc (showString ")")])
    PhiToGraph.Syntax.Abs.CommandBind n1 n2 id_ -> prPrec i 0 (concatD [doc (showString "BIND"), doc (showString "("), prt 0 n1, doc (showString ","), prt 0 n2, doc (showString ","), prt 0 id_, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [PhiToGraph.Syntax.Abs.Command] where
  prt = prtList

instance Print PhiToGraph.Syntax.Abs.Rules where
  prt i = \case
    PhiToGraph.Syntax.Abs.Rules rules -> prPrec i 0 (concatD [prt 0 rules])

instance Print PhiToGraph.Syntax.Abs.Rule where
  prt i = \case
    PhiToGraph.Syntax.Abs.Rule term id_ commands -> prPrec i 0 (concatD [prt 0 term, doc (showString "--"), prt 0 id_, doc (showString "->"), prt 0 commands])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [PhiToGraph.Syntax.Abs.Rule] where
  prt = prtList

